import { useCallback, useEffect, useMemo, useState } from "react";
import { ask, compareEvaluations, deleteDocument, getDocuments, getEvaluations, search, uploadDocument } from "./api";

const METHODS = ["bm25", "tfidf", "embedding", "hybrid"];
const labels = { documents: "资料库", qa: "问答", search: "检索", eval: "评测" };

function useAsync(action, initial = null) {
  const [data, setData] = useState(initial); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const run = useCallback(async (...args) => { setLoading(true); setError(""); try { const value = await action(...args); setData(value); return value; } catch (e) { setError(e.message || "网络错误"); throw e; } finally { setLoading(false); } }, [action]);
  return { data, setData, loading, error, run };
}

function Notice({ error, onRetry, children }) { if (!error && !children) return null; return <div className={error ? "notice error" : "notice"} role={error ? "alert" : undefined}>{error || children}{error && onRetry && <button className="link-button" onClick={onRetry}>重试</button>}</div>; }
function Spinner() { return <span className="spinner" aria-label="加载中" />; }
function Empty({ text = "暂无数据" }) { return <div className="empty">{text}</div>; }
function StatusPill({ status }) { return <span className={`pill ${status || ""}`}>{status || "unknown"}</span>; }

function DocumentsPage() {
  const loader = useAsync(getDocuments, []); const [file, setFile] = useState(null); const [uploading, setUploading] = useState(false); const [uploadError, setUploadError] = useState("");
  const refresh = () => loader.run().catch(() => {});
  useEffect(() => { refresh(); }, []);
  useEffect(() => { const timer = setInterval(() => { if (loader.data?.some(d => ["pending", "processing"].includes(d.status))) refresh(); }, 1800); return () => clearInterval(timer); }, [loader.data]);
  async function onUpload(event) { event.preventDefault(); if (!file) return; setUploading(true); setUploadError(""); try { await uploadDocument(file); setFile(null); event.target.reset(); refresh(); } catch (e) { setUploadError(e.message); } finally { setUploading(false); } }
  async function onDelete(id) { if (!window.confirm("确定删除这份资料吗？")) return; try { await deleteDocument(id); refresh(); } catch (e) { setUploadError(e.message); } }
  return <Page title="资料库" eyebrow="DOCUMENTS" action={<form className="upload" onSubmit={onUpload}><label className="file-picker">{file ? file.name : "选择 PDF / Markdown / TXT"}<input type="file" accept=".pdf,.md,.markdown,.txt" onChange={e => setFile(e.target.files?.[0] || null)} /></label><button className="primary" disabled={!file || uploading}>{uploading ? <Spinner /> : "上传资料"}</button></form>}>
    <Notice error={uploadError || loader.error} onRetry={refresh} />
    {loader.loading && !loader.data?.length ? <Loading /> : !loader.data?.length ? <Empty text="还没有资料，上传第一份课程文档吧" /> : <div className="table-wrap"><table><thead><tr><th>文件</th><th>状态</th><th>Chunks</th><th>大小</th><th>更新时间</th><th /></tr></thead><tbody>{loader.data.map(doc => <tr key={doc.id}><td><strong>{doc.filename}</strong>{doc.error_message && <small className="danger-text">{doc.error_message}</small>}</td><td><StatusPill status={doc.status} /></td><td>{doc.chunk_count}</td><td>{formatBytes(doc.size_bytes)}</td><td>{formatDate(doc.updated_at || doc.created_at)}</td><td><button className="ghost danger" onClick={() => onDelete(doc.id)} disabled={doc.status === "deleted"}>删除</button></td></tr>)}</tbody></table></div>}
  </Page>;
}

function QaPage() { const [question, setQuestion] = useState(""); const [method, setMethod] = useState("hybrid"); const [topK, setTopK] = useState(5); const [answer, setAnswer] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); if (!question.trim()) return; setLoading(true); setError(""); try { setAnswer(await ask({ question, retrieval_method: method, top_k: Number(topK) })); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  return <Page title="问答" eyebrow="ASK YOUR COURSE"><form className="query-form" onSubmit={submit}><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="例如：RAG 的核心流程是什么？" rows="3" /><div className="form-row"><label>检索方法<select value={method} onChange={e => setMethod(e.target.value)}>{METHODS.map(m => <option key={m}>{m}</option>)}</select></label><label>top_k<input type="number" min="1" max="20" value={topK} onChange={e => setTopK(e.target.value)} /></label><button className="primary" disabled={loading || !question.trim()}>{loading ? <><Spinner /> 查询中</> : "获得答案"}</button></div></form><Notice error={error} onRetry={() => submit({ preventDefault() {} })} />{loading && <Loading text="正在检索课程证据…" />}{answer && <AnswerCard answer={answer} />}</Page>;
}
function AnswerCard({ answer }) { return <section className="answer-card"><div className="answer-head"><div><span className="section-label">ANSWER</span><h2>{answer.refused ? "暂时无法回答" : "回答"}</h2></div><StatusPill status={answer.refused ? "refused" : "answered"} /></div><p className="answer-text">{answer.answer}</p>{answer.refused && <div className="refusal"><b>拒答原因</b><code>{answer.refusal_reason || "unknown"}</code></div>}<div className="status-line"><span>请求：<b>{answer.status?.requested_method}</b></span><span>实际：<b>{answer.status?.effective_method}</b></span>{answer.status?.fallback_reason && <span className="warning">Fallback：{answer.status.fallback_reason}</span>}</div>{answer.citations?.length > 0 && <div><span className="section-label">CITATIONS</span><div className="citation-list">{answer.citations.map(c => <article className="citation" key={`${c.chunk_id}-${c.index}`}><div className="citation-meta"><b>[{c.index}] {c.filename}</b><span>{(c.title_path || []).join(" / ") || `Chunk ${c.chunk_index}`}</span><span>score {Number(c.score).toFixed(3)}</span></div><blockquote>{c.quote}</blockquote></article>)}</div></div>}</section>; }

function SearchPage() { const [query, setQuery] = useState(""); const [method, setMethod] = useState("hybrid"); const [results, setResults] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); async function submit(e) { e.preventDefault(); if (!query.trim()) return; setLoading(true); setError(""); try { setResults(await search({ query, retrieval_method: method, top_k: 10 })); } catch (x) { setError(x.message); } finally { setLoading(false); } }
  return <Page title="检索" eyebrow="SEARCH EVIDENCE"><form className="search-bar" onSubmit={submit}><input value={query} onChange={e => setQuery(e.target.value)} placeholder="输入查询，查看命中的原文片段" /><select value={method} onChange={e => setMethod(e.target.value)}>{METHODS.map(m => <option key={m}>{m}</option>)}</select><button className="primary" disabled={loading || !query.trim()}>{loading ? <Spinner /> : "检索"}</button></form><Notice error={error} onRetry={() => submit({ preventDefault() {} })} />{loading && <Loading />}{results && <><div className="result-summary"><b>{results.results?.length || 0}</b> 个结果 · {results.status?.effective_method}{results.status?.fallback_reason && <span className="warning"> · {results.status.fallback_reason}</span>}</div>{!results.results?.length ? <Empty text="没有命中相关片段" /> : <div className="result-list">{results.results.map((r, i) => <article className="result-card" key={r.chunk_id}><div className="result-top"><span className="rank">{i + 1}</span><b>{r.filename}</b><span className="path">{(r.title_path || []).join(" / ") || `Chunk ${r.chunk_index}`}</span><strong>{Number(r.score).toFixed(3)}</strong></div><div className="highlight" dangerouslySetInnerHTML={{ __html: r.highlight || r.content }} /><small>{r.chunk_id} · chunk {r.chunk_index}</small></article>)}</div>}</>}</Page>; }

function EvalPage() { const history = useAsync(getEvaluations, []); const compare = useAsync(compareEvaluations); useEffect(() => { history.run().catch(() => {}); }, []); const runs = compare.data?.runs || history.data || []; const latest = useMemo(() => { const map = {}; runs.forEach(r => { if (!map[r.retrieval_method]) map[r.retrieval_method] = r; }); return METHODS.map(m => map[m]).filter(Boolean); }, [runs]); return <Page title="评测" eyebrow="EVALUATION LAB" action={<button className="primary" onClick={() => compare.run().then(() => history.run()).catch(() => {})} disabled={compare.loading}>{compare.loading ? <><Spinner /> 运行中</> : "运行四方法对比"}</button>}><Notice error={history.error || compare.error} onRetry={() => history.run().catch(() => {})} />{(history.loading && !runs.length) ? <Loading text="加载评测历史…" /> : !runs.length ? <Empty text="还没有评测记录" /> : <><div className="table-wrap"><table className="metrics"><thead><tr><th>方法</th><th>Recall@1</th><th>Recall@5</th><th>MRR</th><th>准确率</th><th>拒答率</th><th>平均延迟</th><th>最近运行</th></tr></thead><tbody>{latest.map(r => <tr key={r.retrieval_method}><td><b>{r.retrieval_method}</b></td><td>{metric(r.metrics, "Recall@1")}</td><td>{metric(r.metrics, "Recall@5")}</td><td>{metric(r.metrics, "MRR")}</td><td>{metric(r.metrics, "answer_accuracy")}</td><td>{metric(r.metrics, "refusal_recall")}</td><td>{metric(r.metrics, "average_latency_ms", "ms")}</td><td>{formatDate(r.created_at)}</td></tr>)}</tbody></table></div><section className="eval-detail"><span className="section-label">LATEST CONFIG SNAPSHOT</span><pre>{JSON.stringify(latest[0]?.config || {}, null, 2)}</pre></section><section className="eval-detail"><span className="section-label">ERROR CASES</span>{latest[0]?.errors?.length ? latest[0].errors.slice(0, 8).map(e => <div className="error-case" key={e.id}><b>{e.id}</b><span>{e.question}</span><small>{e.refusal_reason || "answer mismatch"}</small></div>) : <Empty text="最近评测没有错误案例" />}</section></>}</Page>; }

function Page({ title, eyebrow, action, children }) { return <main><div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1></div>{action}</div>{children}</main>; }
function Loading({ text = "加载中…" }) { return <div className="loading"><Spinner /> {text}</div>; }
function metric(metrics, key, suffix = "") { const v = metrics?.[key]; return v === undefined ? "—" : `${typeof v === "number" && key.includes("accuracy") || key?.startsWith("Recall") || key === "MRR" || key === "refusal_recall" ? `${(v * 100).toFixed(1)}%` : v}${suffix}`; }
function formatBytes(n) { if (n < 1024) return `${n} B`; if (n < 1024 ** 2) return `${(n / 1024).toFixed(1)} KB`; return `${(n / 1024 ** 2).toFixed(1)} MB`; }
function formatDate(value) { return value ? new Date(value).toLocaleString("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "—"; }

export default function App() { const [page, setPage] = useState("documents"); const PageView = { documents: DocumentsPage, qa: QaPage, search: SearchPage, eval: EvalPage }[page]; return <div className="app-shell"><aside><div className="brand"><div className="brand-mark">∴</div><div><b>课程知识</b><small>RAG WORKSPACE</small></div></div><nav>{Object.entries(labels).map(([key, label]) => <button key={key} className={page === key ? "active" : ""} onClick={() => setPage(key)}><span className="nav-icon">{({ documents: "▦", qa: "✦", search: "⌕", eval: "◒" })[key]}</span>{label}</button>)}</nav><div className="sidebar-foot"><span className="online-dot" /> API 在线</div></aside><div className="content"><header><span className="mobile-brand">课程知识</span><span className="api-badge">FastAPI · SQLite</span></header><PageView /></div></div>; }
